""""""""
" VUNDLE
""""""""
set nocompatible              " required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
Plugin 'vim-scripts/indentpython.vim' "Indentation
" Plugin 'Valloric/YouCompleteMe' "Code completion
Plugin 'vim-syntastic/syntastic' "Syntax checker
Plugin 'nvie/vim-flake8' "Linting

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
""""""""""""
" VUNDLE END
""""""""""""

" UTF-8 encoding
set encoding=utf-8

" Enables syntax processing
syntax enable

" Show line numbers
set number

" Number of visual spaces per TAB
set tabstop=4

" Number of spaces in one TAB
set softtabstop=4

" Tabs are spaces
" set expandtab
" Show a cursor line
set cursorline

" Visual autocomplete for command menu
set wildmenu

" Redraw only whne we need to
set lazyredraw

" Highlights parenteses [{()}]
set showmatch

" Search as characters are entered
set incsearch

" Highlight matches
set hlsearch

" Turn of search hightlighting
nnoremap <leader><space> :nohlsearch<CR>

" Leader is comma
let mapleader=","

" Python PEP8 indenting
au BufNewFile,BufRead *.py
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    \ set textwidth=79 |
    \ set expandtab |
    \ set autoindent |
    \ set fileformat=unix

" Easier split navigations
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" More natural split opening
" Add new pane below when doing :sp
set splitbelow
" Add new pane to the right when doing :vsp
set splitright

""""""""""""""""
" netrw settings
""""""""""""""""
" Tree list style
let g:netrw_liststyle = 3
" Width of the file browser
let g:netrw_winsize = 25
" Hide information banner
let g:netrw_banner = 0
" Open file in the previous window to the right
let g:netrw_browse_split = 4
let g:netrw_altv = 1
