""""""""
" VUNDLE
""""""""
set nocompatible              " required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" add all your plugins here (note older versions of Vundle
" used Bundle instead of Plugin)

" ...

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
""""""""""""
" VUNDLE END
""""""""""""

" Enables syntax processing
syntax enable

" Show line numbers
set number

" Number of visual spaces per TAB
set tabstop=4

" Number of spaces in one TAB
set softtabstop=4

" Tabs are spaces
" set expandtab

" Show a cursor line
set cursorline

" Visual autocomplete for command menu
set wildmenu

" Redraw only whne we need to
set lazyredraw

" Highlights parenteses [{()}]
set showmatch

" Search as characters are entered
set incsearch

" Highlight matches
set hlsearch

" Turn of search hightlighting
nnoremap <leader><space> :nohlsearch<CR>

" Leader is comma
let mapleader=","
