""""""""
" VUNDLE
""""""""
set nocompatible              " required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
Plugin 'vim-scripts/indentpython.vim'
"Plugin 'Valloric/YouCompleteMe'
Plugin 'vim-syntastic/syntastic'
Plugin 'nvie/vim-flake8'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
""""""""""""
" VUNDLE END
""""""""""""

" UTF-8 encoding
set encoding=utf-8

" Enables syntax processing
syntax enable

" Show line numbers
set number

" Number of visual spaces per TAB
set tabstop=4

" Number of spaces in one TAB
set softtabstop=4

" Tabs are spaces
" set expandtab
" Show a cursor line
set cursorline

" Visual autocomplete for command menu
set wildmenu

" Redraw only whne we need to
set lazyredraw

" Highlights parenteses [{()}]
set showmatch

" Search as characters are entered
set incsearch

" Highlight matches
set hlsearch

" Turn of search hightlighting
nnoremap <leader><space> :nohlsearch<CR>

" Leader is comma
let mapleader=","

" Python PEP8 indenting
au BufNewFile,BufRead *.py
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    \ set textwidth=79 |
    \ set expandtab |
    \ set autoindent |
    \ set fileformat=unix

